### 회원가입
POST http://3.37.235.204/api/auth/signup
Content-Type: application/json

{
  "email": "test22@example.com",
  "password": "password123",
  "passwordConfirm": "password123",
  "name": "홍길동",
  "company_name": "코드잇"
}

### 로그인
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### 현재 유저 정보 조회 (쿠키 자동 전송)
GET http://localhost:3001/api/auth/me

### 로그아웃
POST http://localhost:3001/api/auth/logout

### 토큰 갱신
POST http://localhost:3001/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "여기에_리프레시_토큰_입력"
}